# Generated by Django 2.0.1 on 2018-01-10 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='거래처명')),
                ('main_items', models.TextField(blank=True, verbose_name='주요 취급 거래품')),
                ('person_in_charge', models.CharField(blank=True, max_length=10, verbose_name='담당자/대표자')),
                ('bank', models.CharField(blank=True, choices=[('기업', '기업은행'), ('국민', '국민은행'), ('하나', 'KEB하나은행'), ('신한', '신한은행'), ('농협', '농협은행'), ('우리', '우리은행'), ('카카', '카카오뱅크'), ('케이', '케이뱅크'), ('외환', '외환은행'), ('씨티', '한국씨티은행')], max_length=4, verbose_name='은행명')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='계좌번호')),
                ('bank_owner', models.CharField(blank=True, max_length=10, verbose_name='계좌주명')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('email_address', models.EmailField(blank=True, max_length=200, verbose_name='이메일')),
                ('office_address', models.CharField(blank=True, max_length=100, verbose_name='주소')),
                ('web_address', models.URLField(blank=True, verbose_name='홈페이지')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='팩스')),
                ('associate_type', models.CharField(choices=[('업체', '업체'), ('개인', '개인')], max_length=5, verbose_name='타입')),
                ('social_security_number', models.CharField(blank=True, max_length=14, verbose_name='주민등록번호')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_list', models.TextField(blank=True, verbose_name='품목')),
                ('total_amount', models.IntegerField(default=0, verbose_name='총액')),
                ('atax_published', models.BooleanField(verbose_name='세금계산서 발행 여부')),
                ('completed', models.BooleanField(default=False, verbose_name='처리 상태')),
                ('completed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='완료일시')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='기안일시')),
                ('last_edited_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='최종수정일')),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Associate', verbose_name='거래처명')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
