# Generated by Django 2.0.1 on 2018-01-18 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20180111_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(choices=[('매장 구매', '매장'), ('온라인 구매', '온라인'), ('기타', '기타')], max_length=10, verbose_name='환불 타입')),
                ('total_amount', models.IntegerField(default=0, verbose_name='총액')),
                ('completed', models.BooleanField(default=False, verbose_name='처리 상태(완료시 체크)')),
                ('completed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='완료일시')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='기안일시')),
                ('bank', models.CharField(blank=True, choices=[('기업', '기업은행'), ('국민', '국민은행'), ('하나', 'KEB하나은행'), ('신한', '신한은행'), ('농협', '농협은행'), ('우리', '우리은행'), ('카카', '카카오뱅크'), ('케이', '케이뱅크'), ('외환', '외환은행'), ('씨티', '한국씨티은행'), ('경남', '경남은행'), ('광주', '광주은행'), ('대구', '대구은행'), ('부산', '부산은행'), ('산림', '산림조합'), ('산업', '산업은행'), ('새마을', '새마을금고'), ('전북', '전북은행'), ('제주', '제주은행'), ('수협', '수협'), ('우체국', '우체국')], max_length=4, verbose_name='은행명')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='계좌번호')),
                ('bank_owner', models.CharField(blank=True, max_length=10, verbose_name='계좌주명')),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='주문번호')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('note', models.TextField(blank=True, verbose_name='내용')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='associate',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='associate',
            name='bank',
            field=models.CharField(blank=True, choices=[('기업', '기업은행'), ('국민', '국민은행'), ('하나', 'KEB하나은행'), ('신한', '신한은행'), ('농협', '농협은행'), ('우리', '우리은행'), ('카카', '카카오뱅크'), ('케이', '케이뱅크'), ('외환', '외환은행'), ('씨티', '한국씨티은행'), ('경남', '경남은행'), ('광주', '광주은행'), ('대구', '대구은행'), ('부산', '부산은행'), ('산림', '산림조합'), ('산업', '산업은행'), ('새마을', '새마을금고'), ('전북', '전북은행'), ('제주', '제주은행'), ('수협', '수협'), ('우체국', '우체국')], max_length=4, verbose_name='은행명'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=14, verbose_name='주민등록번호 (개인일 경우)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='처리 상태(완료시 체크)'),
        ),
    ]
