# Generated by Django 2.0.1 on 2018-03-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180307_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='order_date',
            field=models.DateField(max_length=50, null=True, verbose_name='거래날짜'),
        ),
    ]
